update: all
pin: True
branch: master
schedule: "every week"
search: True
requirements:
  - "requirements.txt"
  - "{{cookiecutter.project_name}}/requirements.txt"
label_prs: requirements
assignees:
 - patdaburu
 - vladdoster
branch_prefix: pyup/
pr_prefix: "Bump requirements"
close_prs: True
