name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tox
        run: |
          tox -e py
      - name: Black
        run: |
          tox -e black
      - name: Flake8
        run: |
          tox -e flake8
      - name: List root dir
        run: |
          ls -al
